Bug correction : now abella fails when trying to redefine a constant. Abella < Type a prop. Abella < Type a prop. Error: a is already defined
This also works for Kind, Define and CoDefine.

I found another bug to correct in the future:
The Define and CoDefine commands add symbols to the signature _before_
checking the definition (with check_defs). Therefore the signature is
extended even if the definition is not well-formed.

Abella < Theorem test : foo.
Error: Unknown constant: foo
Abella < Define foo : prop by foo := bar.
Error: Unknown constant: bar
Abella < Theorem test : foo.

  ============================
   foo

test <